### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Tomanlu** [sachabarber/MVVMDiagramDesigner#5]
Hi, I cannot find any license information inside this repository, only in the tutorial you are referencing to. Would it be possible to add some kind of standard licensing information to this repository such as MIT, Apache 2.0, BSD etc.

**Comment by sachabarber** [comment]
You may do what you want with it use it anyway you like

**Comment by sachabarber** [comment]
What license would be best to say that, I'm not up on licences

**Comment by MudraMartin** [comment]
Hi,
It seems that you want MIT license, that pretty much describes what you said:
Do whatever you want with that but do NOT hold me responsible for it (that's MIT in a nutshell)
https://opensource.org/licenses/MIT

Would it be possible to add this license directly inside repository so it will be shown in Github main repo page?

**Comment by sachabarber** [comment]
@Tomanlu / @LightCZ have added the mix licence for you all do what you like

**Comment by sachabarber** [comment]
@Tomanlu / @LightCZ sorry fat fingered keyboard MIT license
